### ISSUE TITLE
Can't preload after restart app.

### ISSUE THREAD

**Issue by psstevenchan** [HyprMXMobile/Android-SDKs#8]
MoPub 5.15.0 and HyprMX Android 5.1.2
1. Install and Open App
2. Preload HyprMX Ad immediately and it is succeed
3. Don't play the Ad and restart App
4. Preload HyprMX Ad immediately and it is failed

**Comment by psstevenchan** [comment]
Charles Proxy session file inside the zip file
[hyprmx-mopub-android.zip](https://github.com/HyprMXMobile/Android-SDKs/files/5797245/hyprmx-mopub-android.zip)

**Comment by sanderson82** [comment]
This bug has been resolved with version 5.1.2.1 of the HyprMX MoPub adapter.
